### ISSUE TITLE
Não é possível fazer o build para web

### ISSUE THREAD

**Issue by 1mrschneider** [1mrschneider/mermas_digitais_app#17]
Saída no console ao tentar executar com o Chrome:

```
: Error: The argument type 'Future<void> Function()' can't be assigned to the parameter type 'Future<void> Function(App)?'.
firebase_auth_web.dart:92
 - 'Future' is from 'dart:async'.
- 'App' is from 'package:firebase_core_web/src/interop/app.dart' ('../../../AppData/Local/Pub/Cache/hosted/pub.dev/firebase_core_web-2.2.2/lib/src/interop/app.dart').
app.dart:1
    FirebaseCoreWeb.registerService('auth', () async {
                                            ^
```

Saída no terminal ao tentar fazer o build para web com o comando "flutter build web":

```
 Building with sound null safety 

Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is deprecated, please use 'dart 
compile js' instead.
../../../AppData/Local/Pub/Cache/hosted/pub.dev/firebase_auth_web-5.2.8/lib/firebase_auth_web.dart:92:45:  
Error: The argument type 'Future<void> Function()' can't be assigned to the parameter type 'Future<void>   
Function(App)?'.
 - 'Future' is from 'dart:async'.
 - 'App' is from 'package:firebase_core_web/src/interop/app.dart'
 ('../../../AppData/Local/Pub/Cache/hosted/pub.dev/firebase_core_web-2.2.2/lib/src/interop/app.dart').     
    FirebaseCoreWeb.registerService('auth', () async {
                                            ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_speed_dial-6.2.0/lib/src/speed_dial.dart:360:41:   
Warning: Operand of null-aware operation '!' has type 'OverlayState' which excludes null.
 - 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart'
 ('/C:/src/flutter/packages/flutter/lib/src/widgets/overlay.dart').
      if (widget.renderOverlay) Overlay.of(context)!.insert(backgroundOverlay!);
                                        ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_speed_dial-6.2.0/lib/src/speed_dial.dart:361:15:   
Warning: Operand of null-aware operation '!' has type 'OverlayState' which excludes null.
 - 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart'
 ('/C:/src/flutter/packages/flutter/lib/src/widgets/overlay.dart').
      Overlay.of(context)!.insert(overlayEntry!);
              ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/easy_search_bar-2.4.2/lib/easy_search_bar.dart:267:15:     
Warning: Operand of null-aware operation '!' has type 'OverlayState' which excludes null.
 - 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart'
 ('/C:/src/flutter/packages/flutter/lib/src/widgets/overlay.dart').
      Overlay.of(context)!.insert(_overlayEntry!);
              ^
Error: Compilation failed.


#0      Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart:225:7)
<asynchronous suspension>
#1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:847:9)    
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)      
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)      
)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>

Compiling lib\main.dart for the Web...                             13,5s
Exception: Failed to compile application for the Web.
PS C:\Users\mrsch\Documentos\GitHub\mermas_digitais_app> flutter build web

 Building with sound null safety 

Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is deprecated, please use 'dart      
compile js' instead.
../../../AppData/Local/Pub/Cache/hosted/pub.dev/firebase_auth_web-5.2.8/lib/firebase_auth_web.dart:92:45:
Error: The argument type 'Future<void> Function()' can't be assigned to the parameter type 'Future<void>
Function(App)?'.
 - 'Future' is from 'dart:async'.
 - 'App' is from 'package:firebase_core_web/src/interop/app.dart'
 ('../../../AppData/Local/Pub/Cache/hosted/pub.dev/firebase_core_web-2.2.2/lib/src/interop/app.dart').
    FirebaseCoreWeb.registerService('auth', () async {
                                            ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_speed_dial-6.2.0/lib/src/speed_dial.dart:360:41:
Warning: Operand of null-aware operation '!' has type 'OverlayState' which excludes null.
 - 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart'
 ('/C:/src/flutter/packages/flutter/lib/src/widgets/overlay.dart').
      if (widget.renderOverlay) Overlay.of(context)!.insert(backgroundOverlay!);
                                        ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_speed_dial-6.2.0/lib/src/speed_dial.dart:361:15:        
Warning: Operand of null-aware operation '!' has type 'OverlayState' which excludes null.
 - 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart'
 ('/C:/src/flutter/packages/flutter/lib/src/widgets/overlay.dart').
      Overlay.of(context)!.insert(overlayEntry!);
              ^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/easy_search_bar-2.4.2/lib/easy_search_bar.dart:267:15:
Warning: Operand of null-aware operation '!' has type 'OverlayState' which excludes null.
 - 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart'
 ('/C:/src/flutter/packages/flutter/lib/src/widgets/overlay.dart').
      Overlay.of(context)!.insert(_overlayEntry!);
              ^
Error: Compilation failed.


#0      Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart:225:7)
<asynchronous suspension>
#1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:847:9)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
<asynchronous suspension>
#6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:614:16)
<asynchronous suspension>
#7      buildWeb (package:flutter_tools/src/web/compile.dart:53:32)
<asynchronous suspension>
#8      BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:135:5)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)  
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)    
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>

Compiling lib\main.dart for the Web...                             13,1s
Exception: Failed to compile application for the Web.
```
@gzeloni

**Comment by 1mrschneider** [comment]
[Ultimo commit cujo o build/deploy foi realizado com sucesso](https://github.com/1mrschneider/mermas_digitais_app/commit/8b5524157b5a8da9fe847cb41a1dbd138ef8cd05)

**Comment by 1mrschneider** [comment]
Resolvido! Era necessário atualizar a versão do dart utilizada no projeto, fiz isso através do comando "flutter upgrade --force".

[Resolução do problema](https://github.com/1mrschneider/mermas_digitais_app/commit/4be90ac0321fa783954806aababafeb2a5559ada)
